version: '3'

services:
  db:
    container_name: postgres
    image: postgres:12.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=argwatch
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  dbdata:
